### ISSUE TITLE
[feature] store captures on S3 instead of GCP

### ISSUE THREAD

**Issue by vielmetti** [rename-this/vhs#2]
I'm interested in using this with an S3-compatible storage (@Minio) on bare metal, rather than GCP storage.
Any suggestions on where to start?

**Comment by andrewhare** [comment]
To add support for any storage for `vhs` you need to 

1. Implement the [`flow.Source`](https://github.com/rename-this/vhs/blob/main/flow/source.go#L9) and [`flow.Sink`](https://github.com/rename-this/vhs/blob/main/flow/sink.go#L6) interfaces. (Currently, `flow.Sink` is just an `io.WriteCloser`).
1. Add the new source and sink to the [default parser](https://github.com/rename-this/vhs/blob/main/cmd/vhs/main.go#L211).

It probably makes the most sense to implement these with https://github.com/minio/minio-go since we could use the same source/sink to work with S3 as well.
